'use client'

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowRight, Bot, CalendarCheck, Check, Clock3, House, MapPin, MessageCircle, PackageCheck, Search, Send, ShoppingBag, Sparkles, Star, Store, X } from 'lucide-react'
import { useAuth } from './context/AuthContext.jsx'
import { addToCart, assistantCancelBooking, assistantCreateBooking, getAssistantCatalog, getMyBookings, getMyOrders, searchAvailableSlots } from './lib/aura-api.js'

const prompts=['Find nail salons in Ramallah','Find availability tomorrow','Recommend products for dry hair','Track my order','Show my next appointment']
const clean=x=>String(x||'').toLowerCase()
const money=n=>`$${Number(n||0).toFixed(0)}`
const rating=rows=>rows?.length?(rows.reduce((s,x)=>s+Number(x.rating),0)/rows.length).toFixed(1):'New'
const isoDate=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
const dateFromText=t=>/tomorrow/i.test(t)?isoDate(1):/today|tonight/i.test(t)?isoDate(0):null
const timeFromText=t=>{const m=t.match(/(?:after|at|to)\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m)return null;let h=+m[1],min=+(m[2]||0);if(clean(m[3])==='pm'&&h<12)h+=12;if(clean(m[3])==='am'&&h===12)h=0;return h*60+min}

function understand(text,context={}){
  const t=clean(text), next={...context}
  const city=['ramallah','nablus','bethlehem','hebron'].find(x=>t.includes(x)); if(city)next.city=city
  const service=['nails','nail','haircut','hair','makeup','skincare','facial','massage','brows','lashes','pedicure','manicure'].find(x=>t.includes(x));if(service)next.service=service.replace('nails','nail')
  const max=t.match(/(?:under|below|less than)\s*\$?(\d+)/);if(max)next.maxPrice=+max[1]
  if(/home service|at home/.test(t))next.home=true
  if(/highly rated|best rated|top rated/.test(t))next.minRating=4.5
  next.date=dateFromText(t)||next.date;next.after=timeFromText(t)??next.after
  if(/compare/.test(t))return {intent:'compare',context:next}
  if(/cancel/.test(t))return {intent:'cancel',context:next}
  if(/reschedule|move my/.test(t))return {intent:'reschedule',context:next}
  if(/next appointment|my appointment|booking number|who is my specialist|how much is my appointment/.test(t))return {intent:'appointments',context:next}
  if(/where is my order|track|shipped|order arrive/.test(t))return {intent:'orders',context:next}
  if(/product|shampoo|serum|skincare|cheaper alternative|recommend/.test(t))return {intent:'products',context:next}
  if(/policy|how.*booking|payment|promo|delivery|return|review|account/.test(t))return {intent:'faq',context:next}
  if(/book/.test(t))return {intent:'book',context:next}
  return {intent:'salons',context:next}
}

function SalonResult({salon,onBook}){const service=salon.services?.[0];return <article className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><div className="flex gap-3 p-3"><img src={salon.image_url} alt="" className="h-24 w-24 rounded-xl object-cover"/><div className="min-w-0 flex-1"><h3 className="font-display text-lg font-bold">{salon.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-stone-500"><MapPin size={12}/>{salon.address}, {salon.city}</p><div className="mt-2 flex gap-3 text-xs"><b className="text-amber-700">★ {rating(salon.reviews)}</b>{salon.offers_home_service&&<span className="flex items-center gap-1 text-wine-700"><House size={12}/>Home service</span>}</div>{service&&<p className="mt-2 text-sm"><b>{service.name}</b> · {money(service.price)}</p>}</div></div><div className="grid grid-cols-2 border-t border-stone-100"><a href={`/salons/${salon.slug}`} className="px-3 py-3 text-center text-sm font-bold">View Salon</a><button onClick={()=>onBook(salon)} className="bg-wine-700 px-3 py-3 text-sm font-bold text-white">Book Now</button></div></article>}
function ProductResult({product,user,onNotice}){const price=product.discount_price||product.price;return <article className="flex gap-3 rounded-2xl border border-stone-200 bg-white p-3"><img src={product.image_urls?.[0]} alt="" className="h-24 w-24 rounded-xl bg-stone-100 object-cover"/><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-wine-600">{product.brand}</p><h3 className="mt-1 font-bold">{product.name}</h3><p className="mt-1 text-sm font-bold text-wine-700">{money(price)} · ★ {rating(product.reviews)}</p><p className="mt-1 text-xs text-stone-500">{product.stock_quantity>0?`${product.stock_quantity} in stock`:'Out of stock'}{product.salon?.name?` · ${product.salon.name}`:''}</p><div className="mt-2 flex gap-2"><a href={`/products/${product.slug}`} className="rounded-lg border px-3 py-1.5 text-xs font-bold">View</a><button disabled={!user||product.stock_quantity<1} onClick={async()=>{try{await addToCart(user.id,product.id);onNotice('Added to your cart.')}catch(e){onNotice(e.message)}}} className="rounded-lg bg-wine-700 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-40">Add to Cart</button></div></div></article>}
function OrderResult({order}){const latest=[...(order.tracking||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return <article className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex items-center justify-between"><b>{order.order_number}</b><span className="rounded-full bg-wine-50 px-2 py-1 text-xs font-bold capitalize text-wine-700">{order.status.replaceAll('_',' ')}</span></div><p className="mt-2 text-sm">{order.items?.map(x=>`${x.quantity}× ${x.product_name}`).join(', ')}</p><p className="mt-2 text-xs text-stone-500">{latest?.title||'Order received'}{order.estimated_delivery_at?` · Estimated ${new Date(order.estimated_delivery_at).toLocaleDateString()}`:''}</p><a href="/my-orders" className="mt-3 inline-flex text-xs font-bold text-wine-700">View order <ArrowRight size={13}/></a></article>}

export function AssistantExperience({compact=false,onClose}){
 const {user,isAuthenticated}=useAuth();const [catalog,setCatalog]=useState(null),[messages,setMessages]=useState([{role:'assistant',text:'Hi! I’m Aura, your beauty concierge. Tell me what you need and I’ll search Aura’s live salons, appointments and marketplace.'}]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[context,setContext]=useState({}),[pending,setPending]=useState(null);const end=useRef(null)
 useEffect(()=>{getAssistantCatalog().then(setCatalog).catch(e=>setMessages(m=>[...m,{role:'assistant',text:`I couldn't load Aura’s live catalog: ${e.message}`}]))},[]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,busy])
 const say=(text,cards)=>setMessages(m=>[...m,{role:'assistant',text,cards}]);
 async function searchSalons(ctx){let rows=catalog.salons.filter(s=>!ctx.city||clean(s.city)===ctx.city).filter(s=>!ctx.home||s.offers_home_service).map(s=>({...s,services:s.services?.filter(v=>!ctx.service||clean(v.name+' '+v.category).includes(ctx.service))})).filter(s=>!ctx.service||s.services?.length).filter(s=>!ctx.maxPrice||s.services?.some(v=>Number(v.price)<=ctx.maxPrice)).filter(s=>!ctx.minRating||Number(rating(s.reviews))>=ctx.minRating);say(rows.length?`I found ${rows.length} real match${rows.length===1?'':'es'}${ctx.city?` in ${ctx.city[0].toUpperCase()+ctx.city.slice(1)}`:''}. Select Book Now to see live times.`:'No salons currently match all those filters. Try another city, service, or price range.',rows.slice(0,4).map(s=>({type:'salon',data:s})));return rows}
 async function beginBooking(salon,ctx=context){const service=salon.services?.find(s=>!ctx.service||clean(s.name+' '+s.category).includes(ctx.service))||salon.services?.[0];if(!service){say('This salon has no active services available.');return}const date=ctx.date||isoDate(1);const slots=await searchAvailableSlots(salon.id,date);const filtered=ctx.after==null?slots:slots.filter(s=>{const d=new Date(s.slot_at);return d.getHours()*60+d.getMinutes()>=ctx.after});if(!filtered.length){say(`I couldn't find availability on ${date}. Try another date.`);return}say(`These are the live available times for ${service.name} at ${salon.name}.`,filtered.slice(0,5).map(s=>({type:'slot',data:{salon,service,slot:s.slot_at}})))}
 async function handle(raw){const value=raw.trim();if(!value||busy)return;setMessages(m=>[...m,{role:'user',text:value}]);setText('');setBusy(true);try{if(/^confirm$/i.test(value)&&pending){if(pending.type==='cancel'){await assistantCancelBooking(pending.booking.id);say(`Cancelled ${pending.booking.booking_number}. The reserved time has been released.`)}else if(pending.type==='booking'){const b=await assistantCreateBooking({p_salon_id:pending.salon.id,p_service_id:pending.service.id,p_specialist_id:null,p_appointment_at:pending.slot,p_location_type:'salon',p_address:null,p_payment_method:'pay_at_salon'});say(`Your appointment is confirmed. Booking reference: ${b.booking_number}`,[{type:'success',data:b}])}setPending(null);return}
 const parsed=understand(value,context);setContext(parsed.context);if(!catalog)throw new Error('The live catalog is still loading. Please try again in a moment.');
 if(parsed.intent==='salons'||parsed.intent==='compare'){const rows=await searchSalons(parsed.context);if(parsed.intent==='compare'&&rows.length>1)say('Here are the meaningful differences. Compare rating, service prices, location and home-service availability in the cards; Aura does not automatically label one as best.',rows.slice(0,2).map(s=>({type:'salon',data:s})));}
 else if(parsed.intent==='book'){const rows=await searchSalons(parsed.context);if(rows.length===1)await beginBooking(rows[0],parsed.context);else if(!parsed.context.service)say('Which service would you like to book?');}
 else if(parsed.intent==='products'){let rows=catalog.products.filter(p=>!parsed.context.maxPrice||Number(p.discount_price||p.price)<=parsed.context.maxPrice).filter(p=>!parsed.context.service||clean(p.name+' '+p.description+' '+p.category?.name).includes(parsed.context.service));say(rows.length?`I found ${rows.length} products in Aura’s live marketplace.`:'I couldn’t find an in-stock marketplace product matching that request.',rows.slice(0,5).map(p=>({type:'product',data:p})));}
 else if(parsed.intent==='appointments'||parsed.intent==='cancel'||parsed.intent==='reschedule'){if(!isAuthenticated){say('Please sign in so I can securely access only your appointments.',[{type:'login'}]);return}const rows=await getMyBookings(user.id);const upcoming=rows.filter(b=>b.status==='confirmed'&&new Date(b.appointment_at)>new Date()).sort((a,b)=>new Date(a.appointment_at)-new Date(b.appointment_at));if(!upcoming.length){say('You have no upcoming appointments.');return}const b=upcoming[0];if(parsed.intent==='cancel'){setPending({type:'cancel',booking:b});say(`Please confirm cancellation of ${b.booking_number}: ${b.service.name} at ${b.salon.name}, ${new Date(b.appointment_at).toLocaleString()}. Aura’s policy asks for 24 hours’ notice; any applicable fee must be handled by the salon. Type “Confirm” to cancel.`)}else if(parsed.intent==='reschedule'){say('I found your appointment. To keep the original slot safe, choose a new time from My Bookings; it will only change after the new slot is secured.',[{type:'link',href:'/my-bookings',label:'Reschedule safely'}])}else say(`Your next appointment is ${b.service.name} with ${b.specialist_name||'No Preference'} at ${b.salon.name} on ${new Date(b.appointment_at).toLocaleString()}. Booking number: ${b.booking_number}. Total: ${money(Number(b.service_price)+Number(b.additional_fee))}.`,[{type:'link',href:'/my-bookings',label:'View Appointment'}]);}
 else if(parsed.intent==='orders'){if(!isAuthenticated){say('Please sign in so I can securely access only your orders.',[{type:'login'}]);return}const rows=await getMyOrders(user.id);say(rows.length?'Here is your latest order and its newest tracking update.':'You do not have any marketplace orders yet.',rows.slice(0,1).map(o=>({type:'order',data:o})));}
 else {const words=clean(value).split(/\W+/);const faq=catalog.faq.find(f=>words.some(w=>w.length>4&&clean(f.topic+' '+f.question).includes(w)));say(faq?.answer||'I don’t have a verified Aura policy for that question yet. Please contact support rather than relying on an unverified answer.');}
 }catch(e){say(`I couldn't complete that request: ${e.message}. Please try again.`)}finally{setBusy(false)}}
 const renderCard=(c,i)=>{if(c.type==='salon')return <SalonResult key={i} salon={c.data} onBook={s=>beginBooking(s)}/>;if(c.type==='product')return <ProductResult key={i} product={c.data} user={user} onNotice={say}/>;if(c.type==='order')return <OrderResult key={i} order={c.data}/>;if(c.type==='slot'){const {salon,service,slot}=c.data;return <button key={i} onClick={()=>{setPending({type:'booking',salon,service,slot});say(`Please confirm: ${service.name} at ${salon.name}, ${new Date(slot).toLocaleString()}, ${service.duration_minutes} minutes, ${money(service.price)}. Cancellation policy: cancel at least 24 hours ahead. Type “Confirm” to create this booking.`)}} className="rounded-xl border bg-white px-3 py-2 text-sm font-bold text-wine-700">{new Date(slot).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</button>}if(c.type==='success')return <div key={i} className="flex flex-wrap gap-2"><a href="/my-bookings" className="rounded-xl bg-wine-700 px-3 py-2 text-xs font-bold text-white">View Appointment</a><a href={`/salons`} className="rounded-xl border px-3 py-2 text-xs font-bold">Get Directions</a></div>;const href=c.type==='login'?'/login':c.href,label=c.type==='login'?'Sign in':c.label;return <a key={i} href={href} className="inline-flex rounded-xl bg-wine-700 px-3 py-2 text-xs font-bold text-white">{label}</a>}
 return <section className={`flex flex-col overflow-hidden bg-[#fbf8f4] ${compact?'h-[min(680px,calc(100vh-2rem))] rounded-[1.75rem] border border-stone-200 shadow-2xl':'min-h-screen'}`}><header className="flex items-center gap-3 border-b border-stone-200 bg-white px-5 py-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-wine-700 text-white"><Sparkles size={19}/></span><div><h1 className="font-display text-xl font-bold">Aura AI</h1><p className="flex items-center gap-1 text-xs text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Connected to live Aura data</p></div>{onClose&&<button onClick={onClose} className="ml-auto rounded-full p-2 hover:bg-stone-100" aria-label="Close Aura AI"><X size={19}/></button>}</header><div className="flex-1 overflow-y-auto px-4 py-5"><div className="mx-auto max-w-3xl space-y-4">{messages.map((m,i)=><div key={i} className={m.role==='user'?'ml-auto max-w-[82%]':'max-w-[92%]'}><div className={`rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?'rounded-tr-sm bg-wine-700 text-white':'rounded-tl-sm border border-stone-100 bg-white'}`}>{m.text}</div>{m.cards?.length>0&&<div className="mt-2 grid gap-2">{m.cards.map(renderCard)}</div>}</div>)}{busy&&<div className="inline-flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm text-stone-500"><Sparkles size={14} className="animate-pulse"/>Checking Aura’s live data…</div>}<div ref={end}/></div></div><div className="border-t border-stone-200 bg-white p-4"><div className="mx-auto max-w-3xl"><div className="mb-3 flex gap-2 overflow-x-auto pb-1">{prompts.map(p=><button key={p} onClick={()=>handle(p)} className="shrink-0 rounded-full border border-wine-200 bg-wine-50 px-3 py-2 text-xs font-bold text-wine-700">{p}</button>)}</div><form onSubmit={e=>{e.preventDefault();handle(text)}} className="flex items-center gap-2 rounded-2xl border border-stone-200 bg-[#fbf8f4] p-2 focus-within:border-wine-400"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask Aura anything…" className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" aria-label="Message Aura AI"/><button disabled={!text.trim()||busy} className="grid h-10 w-10 place-items-center rounded-xl bg-wine-700 text-white disabled:opacity-40" aria-label="Send"><Send size={17}/></button></form><p className="mt-2 text-center text-[10px] text-stone-400">Aura only performs account changes after your explicit confirmation.</p></div></div></section>
}

export function AssistantPage(){return <AssistantExperience/>}
export function AssistantLauncher(){const [open,setOpen]=useState(false);if(typeof window!=='undefined'&&window.location.pathname==='/assistant')return null;return <><button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-[70] flex items-center gap-2 rounded-full bg-wine-700 px-4 py-3 font-bold text-white shadow-2xl" aria-label="Open Aura AI Assistant"><Sparkles size={18}/><span className="hidden sm:inline">Ask Aura</span></button><AnimatePresence>{open&&<><motion.button initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)} className="fixed inset-0 z-[79] bg-black/25" aria-label="Close assistant backdrop"/><motion.div initial={{opacity:0,y:20,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.98}} className="fixed inset-x-3 bottom-3 z-[80] sm:left-auto sm:right-5 sm:w-[430px]"><AssistantExperience compact onClose={()=>setOpen(false)}/></motion.div></>}</AnimatePresence></>}
