'use client'
import React,{useEffect,useRef,useState}from'react'
import{AnimatePresence,motion}from'framer-motion'
import{ArrowRight,CalendarPlus,House,LocateFixed,MapPin,Send,Sparkles,X}from'lucide-react'
import{useAuth}from'./context/AuthContext.jsx'
import{addToCart,assistantCancelBooking,assistantCreateBooking,assistantRescheduleBooking,getAssistantCatalog,getAssistantConversation,getCancellationQuote,getMyBookings,getMyOrders,saveAssistantMessage,searchAvailableSlots}from'./lib/aura-api.js'

const welcome='Hi! I’m Aura, your beauty concierge. Ask me to find, compare, book, reschedule, cancel, shop, or track an order.'
const prompts=['Find a salon near me','Find nail availability tomorrow','Recommend products for dry hair','Track my order','Show my next appointment']
const low=x=>String(x||'').toLowerCase(),usd=x=>`$${Number(x||0).toFixed(2)}`
const day=n=>{let d=new Date();d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const avg=a=>a?.length?(a.reduce((s,x)=>s+Number(x.rating),0)/a.length).toFixed(1):'New'
const km=(a,b)=>{let r=x=>x*Math.PI/180,d1=r(b.latitude-a.latitude),d2=r(b.longitude-a.longitude),q=Math.sin(d1/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(d2/2)**2;return 12742*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function parse(text,old={}){let t=low(text),c={...old},city=['ramallah','nablus','bethlehem','hebron'].find(x=>t.includes(x)),service=['nails','nail','haircut','hair','makeup','skincare','facial','massage','brows','lashes','pedicure','manicure'].find(x=>t.includes(x)),price=t.match(/(?:under|below|less than)\s*\$?(\d+)/),num=t.match(/au-[a-z0-9-]+/i),tm=t.match(/(?:after|at|to)\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(city)c.city=city;if(service)c.service=service.replace('nails','nail');if(price)c.maxPrice=+price[1];if(num)c.bookingNumber=num[0].toUpperCase();if(/home service|at home/.test(t))c.home=true;if(/highly rated|best rated|top rated/.test(t))c.rating=4.5;c.date=/tomorrow/.test(t)?day(1):/today|tonight/.test(t)?day(0):t.match(/\d{4}-\d{2}-\d{2}/)?.[0]||c.date;if(tm){let h=+tm[1];if(low(tm[3])==='pm'&&h<12)h+=12;if(low(tm[3])==='am'&&h===12)h=0;c.after=`${String(h).padStart(2,'0')}:${tm[2]||'00'}`}let intent=/compare/.test(t)?'compare':/cancel/.test(t)?'cancel':/reschedule|move my|change my appointment/.test(t)?'reschedule':/next appointment|my appointment|booking number|who is my specialist|how much is my appointment/.test(t)?'appointments':/where is my order|track|shipped|order arrive/.test(t)?'orders':/product|shampoo|serum|cheaper alternative|recommend/.test(t)?'products':/policy|how.*booking|payment|promo|delivery|return|review|account/.test(t)?'faq':/book|availability|available time/.test(t)?'book':'salons';return{intent,context:c}}
function calendar(x){let s=new Date(x.slot),e=new Date(s.getTime()+x.service.duration_minutes*60000),f=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),esc=v=>String(v).replace(/[\\;,]/g,'\\$&');let body=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT',`UID:${esc(x.number)}@aura`,`DTSTART:${f(s)}`,`DTEND:${f(e)}`,`SUMMARY:${esc(x.service.name+' at '+x.salon.name)}`,`LOCATION:${esc(x.salon.address+', '+x.salon.city)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));a.download=x.number+'.ics';a.click();URL.revokeObjectURL(a.href)}

const Button=({children,...p})=><button {...p} className="rounded-xl bg-wine-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">{children}</button>
function Salon({s,onBook}){let v=s.services?.[0];return <article className="overflow-hidden rounded-2xl border bg-white"><div className="flex gap-3 p-3"><img src={s.image_url} alt="" className="h-24 w-24 rounded-xl object-cover"/><div><b className="font-display text-lg">{s.name}</b><p className="mt-1 flex gap-1 text-xs text-stone-500"><MapPin size={12}/>{s.address}, {s.city}</p><p className="mt-2 text-xs">★ {avg(s.reviews)} {s.distance!=null&&` · ${s.distance.toFixed(1)} km`} {s.offers_home_service&&' · Home service'}</p>{v&&<p className="mt-2 text-sm">{v.name} · {usd(v.price)}</p>}</div></div><div className="grid grid-cols-2 border-t"><a href={`/salons/${s.slug}`} className="p-3 text-center text-sm font-bold">View Salon</a><button onClick={()=>onBook(s)} className="bg-wine-700 text-sm font-bold text-white">Book Now</button></div></article>}
function Product({p,user,note}){return <article className="flex gap-3 rounded-2xl border bg-white p-3"><img src={p.image_urls?.[0]} alt="" className="h-20 w-20 rounded-xl object-cover"/><div><b>{p.name}</b><p className="text-xs text-stone-500">{p.brand} · {usd(p.discount_price||p.price)} · ★ {avg(p.reviews)}</p><div className="mt-2 flex gap-2"><a href={`/products/${p.slug}`} className="rounded-lg border px-2 py-1 text-xs font-bold">View</a><Button disabled={!user||!p.stock_quantity} onClick={async()=>{try{await addToCart(user.id,p.id);note('Added to cart.')}catch(e){note(e.message)}}}>Add to Cart</Button></div></div></article>}
function Booking({b,action,choose}){return <article className="rounded-2xl border bg-white p-3"><b>{b.service.name}</b><span className="float-right text-xs font-bold text-wine-700">{b.booking_number}</span><p className="mt-1 text-xs text-stone-500">{b.salon.name} · {new Date(b.appointment_at).toLocaleString()}</p><Button onClick={()=>choose(b)}>{action==='cancel'?'Review cancellation':action==='reschedule'?'Choose new time':'View appointment'}</Button></article>}

export function AssistantExperience({compact=false,onClose}){const{user,isAuthenticated,isReady}=useAuth(),[catalog,setCatalog]=useState(),[messages,setMessages]=useState([{role:'assistant',text:welcome}]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[context,setContext]=useState({}),[pending,setPending]=useState(),[conversation,setConversation]=useState(),end=useRef(),loaded=useRef()
useEffect(()=>{getAssistantCatalog().then(setCatalog).catch(e=>setMessages(m=>[...m,{role:'assistant',text:e.message}]))},[])
useEffect(()=>{if(!isReady||loaded.current===(user?.id||'guest'))return;loaded.current=user?.id||'guest';if(user)getAssistantConversation(user.id).then(x=>{setConversation(x.conversation.id);setContext(x.conversation.context||{});if(x.messages.length)setMessages(x.messages.map(m=>({role:m.role,text:m.content}))) });else{try{let x=JSON.parse(localStorage.getItem('aura-assistant-messages'));if(x?.length)setMessages(x)}catch{}}},[isReady,user])
useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy])
const store=(m,c=context)=>{if(user&&conversation)saveAssistantMessage(user.id,conversation,m.role,m.text,c).catch(()=>{});else localStorage.setItem('aura-assistant-messages',JSON.stringify([...messages,m].slice(-50)))}
const say=(text,cards,c=context)=>{let m={role:'assistant',text,cards};setMessages(x=>[...x,m]);store({role:'assistant',text},c)}
const auth=()=>isAuthenticated||(say('Please sign in so I can securely use only your account.',[{type:'login'}]),false)
const locate=()=>{if(!navigator.geolocation)return say('Location is unavailable. Tell me your city instead.');setBusy(true);navigator.geolocation.getCurrentPosition(p=>{let c={...context,location:{latitude:p.coords.latitude,longitude:p.coords.longitude}};setContext(c);say('Location enabled. Nearby results will use real distance.',null,c);setBusy(false)},()=>{say('Location permission was unavailable. Tell me Ramallah, Nablus, Bethlehem, or Hebron.');setBusy(false)},{timeout:10000})}
const salons=c=>catalog.salons.map(s=>({...s,distance:c.location&&s.latitude!=null?km(c.location,{latitude:+s.latitude,longitude:+s.longitude}):null,services:s.services?.filter(v=>!c.service||low(v.name+' '+v.category).includes(c.service))})).filter(s=>(!c.city||low(s.city)===c.city)&&(!c.home||s.offers_home_service)&&(!c.service||s.services.length)&&(!c.maxPrice||s.services.some(v=>+v.price<=c.maxPrice))&&(!c.rating||+avg(s.reviews)>=c.rating)).sort((a,b)=>c.location?(a.distance??9999)-(b.distance??9999):+avg(b.reviews)-+avg(a.reviews))
const showSalons=(c,compare=false)=>{let a=salons(c);say(a.length?(compare?'Here is a neutral comparison using live ratings, location, prices, specialists, and home service.':`I found ${a.length} current matches.`):'No salons match all those filters.',a.slice(0,compare?2:4).map(data=>({type:'salon',data})),c);return a}
async function slots(salon,service,specialist=null,mode='booking',booking=null,c=context){let a=await searchAvailableSlots(salon.id||salon.salon_id,service.id||booking?.service_id,c.date||day(1),specialist?.id||booking?.specialist_id||null,c.after||null);say(a.length?`Choose a non-overlapping time for ${service.name}.`:'No valid times were found. Try another date or specialist.',a.slice(0,8).map(x=>({type:'slot',data:{salon,service,specialist,mode,booking,slot:x.slot_at}})),c)}
async function startBooking(s,c=context){if(!auth())return;let v=s.services.find(x=>!c.service||low(x.name+' '+x.category).includes(c.service))||s.services[0];if(!v)return say('No active service is available.');let cards=[{type:'specialist',data:{salon:s,service:v,specialist:null}},...(s.specialists||[]).map(x=>({type:'specialist',data:{salon:s,service:v,specialist:x}}))];say('Choose a specialist or No Preference before selecting a time.',cards,c)}
const matches=(a,c)=>a.filter(b=>b.status==='confirmed'&&new Date(b.appointment_at)>new Date()).filter(b=>!c.bookingNumber||b.booking_number===c.bookingNumber).filter(b=>!c.service||low(b.service.name+' '+b.service.category).includes(c.service)).filter(b=>!c.date||b.appointment_at.slice(0,10)===c.date)
async function chooseAction(intent,c){if(!auth())return;let a=matches(await getMyBookings(user.id),c);if(!a.length)return say('No upcoming appointment matches those details.');if(a.length>1)return say('Multiple appointments match. Choose the exact one.',a.map(data=>({type:'booking',action:intent,data})),c);prepare(intent,a[0],c)}
async function prepare(intent,b,c=context){if(intent==='appointments')return say(`Booking ${b.booking_number}: ${b.service.name}, ${b.specialist_name||'No Preference'}, ${b.salon.name}, ${new Date(b.appointment_at).toLocaleString()}, total ${usd(+b.service_price + +b.additional_fee)}.`,[{type:'links',data:b}],c);if(intent==='cancel'){let q=await getCancellationQuote(b.id);if(!q?.can_cancel)return say('This appointment cannot be cancelled.');setPending({type:'cancel',booking:b,quote:q});return say(`Confirm cancellation of ${b.booking_number}. Fee: ${usd(q.fee)}. ${q.policy}`,[{type:'confirm'}],c)}slots(b.salon,b.service,b.specialist,'reschedule',b,c)}
async function confirm(){if(!pending)return;if(pending.type==='cancel'){let b=await assistantCancelBooking(pending.booking.id);say(`Cancelled ${b.booking_number}. The slot is released.`)}else if(pending.type==='reschedule'){let b=await assistantRescheduleBooking(pending.booking.id,pending.slot);say(`Booking ${b.booking_number} moved to ${new Date(b.appointment_at).toLocaleString()}.`,[{type:'confirmed',data:{number:b.booking_number,salon:pending.booking.salon,service:pending.booking.service,slot:b.appointment_at}}])}else{let b=await assistantCreateBooking({p_salon_id:pending.salon.id,p_service_id:pending.service.id,p_specialist_id:pending.specialist?.id||null,p_appointment_at:pending.slot,p_location_type:'salon',p_address:null,p_payment_method:'pay_at_salon'});say(`Confirmed. Booking reference: ${b.booking_number}.`,[{type:'confirmed',data:{number:b.booking_number,salon:pending.salon,service:pending.service,slot:b.appointment_at}}])}setPending(null)}
async function send(raw){let value=raw.trim();if(!value||busy)return;let m={role:'user',text:value};setMessages(x=>[...x,m]);setText('');setBusy(true);try{let p=parse(value,context);setContext(p.context);store(m,p.context);if(!catalog)throw Error('Live data is still loading.');if(/^confirm$/i.test(value)&&pending)await confirm();else if(/near me/.test(low(value))&&!p.context.location)say('Allow location access or tell me your city.',[{type:'location'}],p.context);else if(p.intent==='salons')showSalons(p.context);else if(p.intent==='compare')showSalons(p.context,true);else if(p.intent==='book'){let a=salons(p.context);if(!p.context.service)say('Which service would you like?',null,p.context);else if(a.length===1)startBooking(a[0],p.context);else say(a.length?'Choose a salon to see real specialists and times.':'No salons match.',a.slice(0,4).map(data=>({type:'salon',data})),p.context)}else if(['appointments','cancel','reschedule'].includes(p.intent))await chooseAction(p.intent,p.context);else if(p.intent==='products'){let a=catalog.products.filter(x=>x.stock_quantity>0).filter(x=>!p.context.maxPrice||+(x.discount_price||x.price)<=p.context.maxPrice).filter(x=>!p.context.service||low(x.name+' '+x.description+' '+x.category?.name+' '+x.benefits?.join(' ')).includes(p.context.service));say(a.length?`I found ${a.length} in-stock products.`:'No in-stock product matches.',a.slice(0,5).map(data=>({type:'product',data})),p.context)}else if(p.intent==='orders'){if(!auth())return;let a=await getMyOrders(user.id);say(a.length?'Here is your latest order and tracking update.':'You have no orders.',a.slice(0,1).map(data=>({type:'order',data})),p.context)}else{let words=low(value).split(/\W+/),q=catalog.faq.find(x=>words.some(w=>w.length>4&&low(x.topic+' '+x.question).includes(w)));say(q?.answer||'I do not have a verified policy answer. Please contact support.',null,p.context)}}catch(e){say(`I couldn't complete that request: ${e.message}`)}finally{setBusy(false)}}
function card(c,i){if(c.type==='salon')return <Salon key={i}s={c.data}onBook={startBooking}/>;if(c.type==='product')return <Product key={i}p={c.data}user={user}note={say}/>;if(c.type==='booking')return <Booking key={i}b={c.data}action={c.action}choose={b=>prepare(c.action,b)}/>;if(c.type==='specialist')return <Button key={i}onClick={()=>slots(c.data.salon,c.data.service,c.data.specialist)}>{c.data.specialist?`${c.data.specialist.specialty} · ★ ${c.data.specialist.rating}`:'No Preference'}</Button>;if(c.type==='slot')return <Button key={i}onClick={()=>{let d=c.data,set=d.mode==='reschedule'?{type:'reschedule',booking:d.booking,slot:d.slot}:{type:'booking',...d};setPending(set);say(d.mode==='reschedule'?`Confirm moving ${d.booking.booking_number} to ${new Date(d.slot).toLocaleString()}. The old slot stays reserved until this succeeds.`:`Confirm ${d.service.name} at ${d.salon.name}, ${new Date(d.slot).toLocaleString()}, ${d.service.duration_minutes} minutes, ${usd(d.service.price)}, ${d.specialist?.specialty||'No Preference'}. Cancellation: free until 24 hours before; then 20%.`,[{type:'confirm'}])}}>{new Date(c.data.slot).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Button>;if(c.type==='confirm')return <div key={i}className="flex gap-2"><Button onClick={confirm}>Confirm</Button><button onClick={()=>{setPending(null);say('No changes were made.')}}className="rounded-xl border px-3 py-2 text-xs font-bold">Keep current</button></div>;if(c.type==='location')return <Button key={i}onClick={locate}><LocateFixed size={13}/> Use my location</Button>;if(c.type==='links'||c.type==='confirmed'){let b=c.data,x=c.type==='links'?{number:b.booking_number,salon:b.salon,service:b.service,slot:b.appointment_at}:b;return <div key={i}className="flex flex-wrap gap-2"><a href="/my-bookings"className="rounded-xl bg-wine-700 px-3 py-2 text-xs font-bold text-white">View Appointment</a><button onClick={()=>calendar(x)}className="rounded-xl border px-3 py-2 text-xs font-bold"><CalendarPlus size={13}/> Add to Calendar</button><a target="_blank"rel="noreferrer"href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.salon.address+', '+x.salon.city)}`}className="rounded-xl border px-3 py-2 text-xs font-bold">Directions</a></div>}if(c.type==='order'){let o=c.data,last=[...(o.tracking||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return <article key={i}className="rounded-2xl border bg-white p-3"><b>{o.order_number}</b><p className="text-sm capitalize">{o.status.replaceAll('_',' ')}</p><p className="text-xs text-stone-500">{last?.title||'Order received'}</p></article>}return <a key={i}href="/login"className="rounded-xl bg-wine-700 px-3 py-2 text-xs font-bold text-white">Sign in</a>}
return <section className={`flex flex-col overflow-hidden bg-[#fbf8f4] ${compact?'h-[min(680px,calc(100vh-2rem))] rounded-[1.75rem] border shadow-2xl':'min-h-screen'}`}><header className="flex items-center gap-3 border-b bg-white px-5 py-4"><i className="grid h-11 w-11 place-items-center rounded-full bg-wine-700 text-white"><Sparkles size={19}/></i><div><h1 className="font-display text-xl font-bold">Aura AI</h1><p className="text-xs text-emerald-700">● Connected to live Aura data</p></div>{onClose&&<button onClick={onClose}className="ml-auto"><X/></button>}</header><main className="flex-1 overflow-y-auto p-4"><div className="mx-auto max-w-3xl space-y-4">{messages.map((m,i)=><div key={i}className={m.role==='user'?'ml-auto max-w-[82%]':'max-w-[92%]'}><div className={`rounded-2xl px-4 py-3 text-sm ${m.role==='user'?'bg-wine-700 text-white':'border bg-white'}`}>{m.text}</div>{m.cards&&<div className="mt-2 grid gap-2">{m.cards.map(card)}</div>}</div>)}{busy&&<p>Checking live data…</p>}<div ref={end}/></div></main><footer className="border-t bg-white p-4"><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-2 overflow-x-auto">{prompts.map(p=><button key={p}onClick={()=>send(p)}className="shrink-0 rounded-full bg-wine-50 px-3 py-2 text-xs font-bold text-wine-700">{p}</button>)}</div><form onSubmit={e=>{e.preventDefault();send(text)}}className="flex rounded-2xl border p-2"><input value={text}onChange={e=>setText(e.target.value)}placeholder="Ask Aura anything…"className="min-w-0 flex-1 bg-transparent px-2 outline-none"/><Button disabled={!text.trim()||busy}><Send size={16}/></Button></form><p className="mt-2 text-center text-[10px] text-stone-400">Account changes require explicit confirmation.</p></div></footer></section>}
export function AssistantPage(){return <AssistantExperience/>}
export function AssistantLauncher(){const[open,setOpen]=useState(false),[hide,setHide]=useState(false);useEffect(()=>{setHide(location.pathname==='/assistant')},[]);return <><button aria-hidden={hide} style={{display:hide?'none':undefined}} onClick={()=>setOpen(true)}className="fixed bottom-5 right-5 z-[70] rounded-full bg-wine-700 px-4 py-3 font-bold text-white shadow-2xl"><Sparkles className="inline"size={18}/> Ask Aura</button><AnimatePresence>{open&&<><motion.button initial={{opacity:0}}animate={{opacity:1}}exit={{opacity:0}}onClick={()=>setOpen(false)}className="fixed inset-0 z-[79] bg-black/25"/><motion.div initial={{opacity:0,y:20}}animate={{opacity:1,y:0}}exit={{opacity:0,y:20}}className="fixed inset-x-3 bottom-3 z-[80] sm:left-auto sm:right-5 sm:w-[430px]"><AssistantExperience compact onClose={()=>setOpen(false)}/></motion.div></>}</AnimatePresence></>}
