import React, { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { CalendarCheck, Check, CheckCircle2, Clock3, House, Info, MapPin, Navigation, RefreshCw, Sparkles, Star, Store, X, XCircle } from 'lucide-react'
import { salons } from './salons.jsx'

const initialBookings = [
  { id:'AU-28491', salonId:'luna-beauty', salon:'Luna Beauty Studio', service:'Hair Coloring', specialist:'Layla Nasser', date:'September 5, 2026', iso:'2026-09-05', time:'06:00 PM', duration:'2 hours', location:'At Salon', address:'12 Rose Avenue, Downtown', payment:'Pay Online', paymentStatus:'Paid', price:60, fee:0, status:'Confirmed' },
  { id:'AU-28604', salonId:'maison-glow', salon:'Maison Glow', service:'Facial Treatment', specialist:'Maya Khalil', date:'September 11, 2026', iso:'2026-09-11', time:'03:00 PM', duration:'1 hour 15 min', location:'Home Service', address:'18 Jasmine Street, Al-Masyoun', payment:'Cash on Home Service', paymentStatus:'Due at appointment', price:45, fee:12, status:'Confirmed' },
  { id:'AU-27118', salonId:'muse-studio', salon:'Muse Nail Bar', service:'Manicure', specialist:'Noura Saleh', date:'August 18, 2026', iso:'2026-08-18', time:'10:30 AM', duration:'45 minutes', location:'At Salon', address:'7 Garden Lane, City Center', payment:'Cash at Salon', paymentStatus:'Paid', price:20, fee:0, status:'Completed' },
  { id:'AU-26842', salonId:'serene-spa', salon:'Serene Spa', service:'Facial & Massage', specialist:'Dina Omar', date:'August 2, 2026', iso:'2026-08-02', time:'01:30 PM', duration:'1 hour 30 min', location:'At Salon', address:'24 Olive Road, Old Town', payment:'Pay Online', paymentStatus:'Refunded', price:70, fee:0, status:'Cancelled' },
]

const salonImages = Object.fromEntries(salons.map(s => [s.id, s.image]))
const tabNames = ['Upcoming', 'Completed', 'Cancelled']
const availableTimes = ['09:00 AM','10:30 AM','12:00 PM','01:30 PM','03:00 PM','04:30 PM','06:00 PM']

export function BookingStatusBadge({ status }) {
  const styles = status === 'Completed' ? 'bg-emerald-50 text-emerald-700' : status === 'Cancelled' ? 'bg-stone-100 text-stone-600' : 'bg-wine-50 text-wine-700'
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${styles}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>
}

export function BookingTabs({ active, onChange, counts }) {
  return <div className="flex overflow-x-auto border-b border-stone-200" role="tablist" aria-label="Booking status">
    {tabNames.map(tab => <button key={tab} role="tab" aria-selected={active === tab} onClick={() => onChange(tab)} className={`relative min-w-fit px-5 py-4 text-sm font-bold transition ${active === tab ? 'text-wine-700' : 'text-stone-500 hover:text-wine-700'}`}>{tab}<span className="ml-2 rounded-full bg-stone-100 px-2 py-0.5 text-[11px]">{counts[tab]}</span>{active === tab && <motion.span layoutId="booking-tab" className="absolute inset-x-2 bottom-0 h-0.5 rounded-full bg-wine-700" />}</button>)}
  </div>
}

function ActionButton({ children, tone='secondary', ...props }) {
  const style = tone === 'primary' ? 'bg-wine-700 text-white hover:bg-wine-800' : tone === 'danger' ? 'border border-red-200 text-red-700 hover:bg-red-50' : 'border border-stone-200 text-charcoal hover:border-wine-200 hover:bg-wine-50'
  return <button {...props} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${style}`}>{children}</button>
}

export function BookingCard({ booking, onDetails, onReschedule, onCancel, onReview }) {
  const upcoming = booking.status === 'Confirmed'
  return <motion.article layout initial={{ opacity:0, y:12 }} animate={{ opacity:1, y:0 }} className="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-[0_12px_40px_rgba(60,35,31,.06)] transition hover:-translate-y-0.5 hover:shadow-[0_18px_50px_rgba(60,35,31,.10)]">
    <div className="grid md:grid-cols-[220px_1fr]">
      <img src={salonImages[booking.salonId]} alt={`${booking.salon} interior`} className="h-52 w-full object-cover md:h-full" />
      <div className="p-5 sm:p-6">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-wine-600">Booking #{booking.id}</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-.03em]">{booking.salon}</h2><p className="mt-1 font-semibold text-stone-600">{booking.service}</p></div><BookingStatusBadge status={booking.status} /></div>
        <dl className="mt-5 grid gap-3 text-sm text-stone-600 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-stone-400">Specialist</dt><dd className="mt-0.5 font-semibold text-charcoal">{booking.specialist}</dd></div><div><dt className="text-xs text-stone-400">Date & time</dt><dd className="mt-0.5 font-semibold text-charcoal">{booking.date}<br/>{booking.time}</dd></div><div><dt className="text-xs text-stone-400">Location</dt><dd className="mt-0.5 flex items-center gap-1 font-semibold text-charcoal">{booking.location === 'Home Service' ? <House size={14}/> : <Store size={14}/>} {booking.location}</dd></div><div><dt className="text-xs text-stone-400">Total</dt><dd className="mt-0.5 font-display text-xl font-bold text-wine-700">${booking.price + booking.fee}</dd></div></dl>
        <div className="mt-6 flex flex-wrap gap-2">
          {upcoming && <><ActionButton tone="primary" onClick={() => onDetails(booking)}>View Details</ActionButton><ActionButton onClick={() => onReschedule(booking)}>Reschedule</ActionButton><ActionButton tone="danger" onClick={() => onCancel(booking)}>Cancel Booking</ActionButton><a href={booking.location === 'Home Service' ? `https://maps.google.com/?q=${encodeURIComponent(booking.address)}` : `https://maps.google.com/?q=${encodeURIComponent(booking.salon)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-xl border border-stone-200 px-4 py-2.5 text-sm font-bold transition hover:border-wine-200 hover:bg-wine-50">{booking.location === 'Home Service' ? <><MapPin size={15}/>View Address</> : <><Navigation size={15}/>Get Directions</>}</a></>}
          {booking.status === 'Completed' && <><a href={`/booking/${booking.salonId}?service=${encodeURIComponent(booking.service)}`} className="inline-flex items-center gap-1.5 rounded-xl bg-wine-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-wine-800"><RefreshCw size={15}/>Book Again</a><ActionButton onClick={() => onReview(booking)}>Leave a Review</ActionButton><ActionButton onClick={() => onDetails(booking)}>View Details</ActionButton></>}
          {booking.status === 'Cancelled' && <><a href={`/booking/${booking.salonId}?service=${encodeURIComponent(booking.service)}`} className="inline-flex items-center gap-1.5 rounded-xl bg-wine-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-wine-800"><RefreshCw size={15}/>Book Again</a><ActionButton onClick={() => onDetails(booking)}>View Details</ActionButton></>}
        </div>
      </div>
    </div>
  </motion.article>
}

function Modal({ children, title, onClose, width='max-w-xl' }) {
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-wine-950/60 p-4 backdrop-blur-sm" onMouseDown={e => e.target === e.currentTarget && onClose()}><motion.div initial={{ opacity:0, scale:.96, y:12 }} animate={{ opacity:1, scale:1, y:0 }} role="dialog" aria-modal="true" aria-label={title} className={`relative my-6 w-full ${width} rounded-3xl bg-white p-6 shadow-2xl sm:p-8`}><button onClick={onClose} aria-label="Close dialog" className="absolute right-5 top-5 rounded-full p-2 text-stone-400 hover:bg-stone-100 hover:text-charcoal"><X size={19}/></button>{children}</motion.div></div>
}

export function BookingTimeline({ status }) {
  const steps = ['Booked','Confirmed','Upcoming','Completed']; const active = status === 'Completed' ? 4 : status === 'Cancelled' ? 1 : 3
  return <div className="mt-6 grid grid-cols-4 gap-1">{steps.map((step,i) => <div key={step} className="text-center"><div className={`mx-auto grid h-7 w-7 place-items-center rounded-full ${i < active ? 'bg-wine-700 text-white' : 'bg-stone-100 text-stone-400'}`}>{i < active ? <Check size={14}/> : i+1}</div><div className={`mt-2 text-[10px] font-bold sm:text-xs ${i < active ? 'text-wine-700' : 'text-stone-400'}`}>{step}</div>{i < 3 && <span className={`absolute hidden h-px ${i < active-1 ? 'bg-wine-300' : 'bg-stone-200'}`}/>}</div>)}</div>
}

export function BookingDetailsModal({ booking, onClose }) {
  const rows = [['Booking number',`#${booking.id}`],['Salon',booking.salon],['Service',booking.service],['Specialist',booking.specialist],['Date',booking.date],['Time',booking.time],['Duration',booking.duration],['Location',booking.location],['Payment method',booking.payment],['Payment status',booking.paymentStatus]]
  return <Modal title="Booking details" onClose={onClose}><p className="text-xs font-bold uppercase tracking-[.14em] text-wine-600">Appointment details</p><h2 className="mt-2 font-display text-3xl font-bold">{booking.salon}</h2><BookingTimeline status={booking.status}/><dl className="mt-7 divide-y divide-stone-100 rounded-2xl bg-[#faf7f3] px-5">{rows.map(([k,v]) => <div key={k} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-stone-500">{k}</dt><dd className="text-right font-semibold">{v}</dd></div>)}{booking.location === 'Home Service' && <div className="flex justify-between gap-4 py-3 text-sm"><dt className="text-stone-500">Address</dt><dd className="text-right font-semibold">{booking.address}</dd></div>}</dl><div className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><span>Service price</span><b>${booking.price}</b></div><div className="flex justify-between"><span>Additional fees</span><b>${booking.fee}</b></div><div className="flex justify-between border-t pt-3 text-base"><span className="font-bold">Total</span><strong className="text-wine-700">${booking.price + booking.fee}</strong></div></div><div className="mt-5 flex justify-between"><BookingStatusBadge status={booking.status}/><ActionButton tone="primary" onClick={onClose}>Done</ActionButton></div></Modal>
}

export function RescheduleModal({ booking, onClose, onConfirm }) {
  const dates = useMemo(() => Array.from({length:5},(_,i) => { const d=new Date(2026,8,8+i); return { iso:d.toISOString().slice(0,10), day:d.toLocaleDateString('en-US',{weekday:'short'}), num:d.getDate(), label:d.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}) } }),[])
  const [date,setDate]=useState(dates[0]); const [time,setTime]=useState('10:30 AM')
  return <Modal title="Reschedule appointment" onClose={onClose}><p className="text-xs font-bold uppercase tracking-[.14em] text-wine-600">Reschedule</p><h2 className="mt-2 font-display text-3xl font-bold">Choose a new time</h2><p className="mt-2 text-sm text-stone-500">{booking.service} at {booking.salon}</p><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{dates.map(d => <button key={d.iso} onClick={() => setDate(d)} className={`min-w-16 rounded-2xl border px-3 py-3 text-center transition ${date.iso===d.iso?'border-wine-700 bg-wine-700 text-white':'border-stone-200 hover:border-wine-300'}`}><span className="block text-xs">{d.day}</span><b className="mt-1 block text-xl">{d.num}</b></button>)}</div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{availableTimes.map((t,i) => <button disabled={i===2||i===5} key={t} onClick={() => setTime(t)} className={`rounded-xl border px-3 py-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:bg-stone-100 disabled:text-stone-300 ${time===t?'border-wine-700 bg-wine-50 text-wine-700':'border-stone-200'}`}>{t}</button>)}</div><div className="mt-7 flex justify-end gap-2"><ActionButton onClick={onClose}>Keep Current</ActionButton><ActionButton tone="primary" onClick={() => onConfirm(date,time)}>Confirm New Appointment</ActionButton></div></Modal>
}

export function CancelBookingModal({ booking, onClose, onConfirm }) { return <Modal title="Cancel appointment" onClose={onClose} width="max-w-md"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-red-50 text-red-600"><XCircle size={27}/></div><h2 className="mt-5 text-center font-display text-2xl font-bold">Are you sure you want to cancel this appointment?</h2><p className="mt-3 text-center text-sm text-stone-500">Your {booking.service} appointment at {booking.salon} is scheduled for {booking.date} at {booking.time}.</p><div className="mt-7 grid gap-2 sm:grid-cols-2"><ActionButton onClick={onClose}>Keep Appointment</ActionButton><ActionButton tone="danger" onClick={onConfirm}>Cancel Booking</ActionButton></div></Modal> }

export function ReviewModal({ booking, onClose, onSubmit }) {
  const [rating,setRating]=useState(0); const [comment,setComment]=useState('')
  return <Modal title="Leave a review" onClose={onClose} width="max-w-md"><p className="text-xs font-bold uppercase tracking-[.14em] text-wine-600">Share your experience</p><h2 className="mt-2 font-display text-3xl font-bold">How was your visit?</h2><p className="mt-2 text-sm text-stone-500">{booking.service} at {booking.salon}</p><div className="mt-6 flex gap-2" aria-label="Rating">{[1,2,3,4,5].map(n => <button key={n} onClick={() => setRating(n)} aria-label={`${n} star${n>1?'s':''}`} className="p-1"><Star size={30} className={n<=rating?'fill-amber-400 text-amber-400':'text-stone-300'}/></button>)}</div><label className="mt-5 block text-sm font-bold">Your comments<textarea value={comment} onChange={e=>setComment(e.target.value)} rows="4" placeholder="Tell us what you loved..." className="mt-2 w-full resize-none rounded-xl border border-stone-200 bg-[#faf7f3] px-4 py-3 font-normal outline-none focus:border-wine-500 focus:ring-2 focus:ring-wine-100"/></label><button disabled={!rating} onClick={() => onSubmit(rating,comment)} className="btn-primary mt-6 w-full rounded-xl disabled:cursor-not-allowed disabled:opacity-40">Submit Review</button></Modal>
}

export function EmptyBookingsState({ tab }) { return <div className="rounded-3xl border border-dashed border-wine-200 bg-white px-6 py-16 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-wine-50 text-wine-700"><CalendarCheck size={28}/></div><h2 className="mt-5 font-display text-2xl font-bold">No {tab.toLowerCase()} bookings yet</h2><p className="mx-auto mt-2 max-w-md text-stone-500">Discover salons and book your next beauty appointment with Aura.</p><a href="/salons" className="btn-primary mt-6 inline-flex rounded-xl">Discover Salons</a></div> }

export function MyBookingsPage() {
  const [bookings,setBookings]=useState(initialBookings); const [active,setActive]=useState('Upcoming'); const [dialog,setDialog]=useState(null); const [notice,setNotice]=useState('')
  const visible=bookings.filter(b => active==='Upcoming' ? b.status==='Confirmed' : b.status===active)
  const counts={Upcoming:bookings.filter(b=>b.status==='Confirmed').length,Completed:bookings.filter(b=>b.status==='Completed').length,Cancelled:bookings.filter(b=>b.status==='Cancelled').length}
  const showNotice = text => { setNotice(text); window.setTimeout(() => setNotice(''),3500) }
  const cancel = () => { setBookings(bs=>bs.map(b=>b.id===dialog.booking.id?{...b,status:'Cancelled',paymentStatus:b.paymentStatus==='Paid'?'Refund pending':b.paymentStatus}:b)); setDialog(null); setActive('Cancelled'); showNotice('Appointment cancelled successfully.') }
  const reschedule = (date,time) => { setBookings(bs=>bs.map(b=>b.id===dialog.booking.id?{...b,date:date.label,iso:date.iso,time}:b)); setDialog(null); showNotice('Your appointment has been rescheduled.') }
  return <div className="min-h-screen bg-[#fbf8f4] text-charcoal"><header className="sticky top-0 z-30 border-b border-stone-200/80 bg-[#fbf8f4]/90 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between"><a href="/" className="font-display text-3xl font-bold tracking-[-.06em] text-wine-800">Aura<span className="text-blush-500">.</span></a><nav className="flex items-center gap-2 sm:gap-3"><a href="/salons" className="hidden rounded-xl px-4 py-2.5 text-sm font-bold text-stone-600 hover:bg-white sm:inline-flex">Discover Salons</a><a href="/dashboard" className="rounded-xl border border-stone-200 bg-white px-4 py-2.5 text-sm font-bold hover:border-wine-200">Dashboard</a></nav></div></header><main className="container py-10 sm:py-14"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-wine-600"><Sparkles size={14}/>Your beauty schedule</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.05em] sm:text-5xl">My Bookings</h1><p className="mt-3 text-stone-500">Manage your upcoming and previous beauty appointments.</p></div><a href="/salons" className="btn-primary rounded-xl">Book an Appointment</a></div>{notice && <motion.div initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} className="mt-6 flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><CheckCircle2 size={19}/>{notice}</motion.div>}<section className="mt-8 overflow-hidden rounded-3xl border border-stone-200 bg-white"><BookingTabs active={active} onChange={setActive} counts={counts}/></section><section className="mt-6 space-y-5">{visible.length ? visible.map(b=><BookingCard key={b.id} booking={b} onDetails={booking=>setDialog({type:'details',booking})} onReschedule={booking=>setDialog({type:'reschedule',booking})} onCancel={booking=>setDialog({type:'cancel',booking})} onReview={booking=>setDialog({type:'review',booking})}/>) : <EmptyBookingsState tab={active}/>}</section></main><footer className="mt-12 border-t border-stone-200 py-8"><div className="container flex flex-wrap justify-between gap-3 text-sm text-stone-500"><span>© 2026 Aura Beauty Technologies</span><span className="flex items-center gap-2"><Info size={14}/>Need help? Support is available 24/7.</span></div></footer>{dialog?.type==='details'&&<BookingDetailsModal booking={dialog.booking} onClose={()=>setDialog(null)}/>} {dialog?.type==='reschedule'&&<RescheduleModal booking={dialog.booking} onClose={()=>setDialog(null)} onConfirm={reschedule}/>} {dialog?.type==='cancel'&&<CancelBookingModal booking={dialog.booking} onClose={()=>setDialog(null)} onConfirm={cancel}/>} {dialog?.type==='review'&&<ReviewModal booking={dialog.booking} onClose={()=>setDialog(null)} onSubmit={()=>{setDialog(null);showNotice('Thank you! Your review has been submitted.')}}/>}</div>
}
