import React, { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Bell, CalendarCheck, ChevronDown, Clock3, Compass, Gift, Heart, Home, LogOut, MapPin, Navigation, Search, Settings, ShoppingBag, Sparkles, Star, UserRound, X } from 'lucide-react'
import { useAuth, navigate } from './context/AuthContext.jsx'
import { getFavorites, getMyBookings, getSalons, toggleFavorite } from './lib/aura-api.js'
import { mapDatabaseBooking } from './bookings.jsx'
import { mapDatabaseSalon, SalonCard } from './salons.jsx'

const quickActions=[
  [Search,'Discover Salons','Find your perfect beauty destination.','/salons'],
  [CalendarCheck,'Book Appointment','Choose a service and time.','/salons'],
  [Clock3,'My Bookings','Manage upcoming appointments.','/my-bookings'],
  [Heart,'Favorites','Return to salons you love.','/favorites'],
]
const serviceCategories=[['✂','Hair'],['◇','Nails'],['✦','Makeup'],['◌','Skincare'],['⌁','Lashes'],['⌒','Brows'],['♨','Spa']]
const offers=[
  {discount:'20% OFF',title:'Your First Hair Appointment',copy:'Meet a new favorite stylist and enjoy a little extra glow.',expires:'Ends September 30',tone:'from-[#6c2938] to-[#9a5261]'},
  {discount:'FREE DELIVERY',title:'Beauty Orders Over $50',copy:'Fill your beauty shelf—we will handle the delivery.',expires:'This month only',tone:'from-[#8b684d] to-[#c29b78]'},
  {discount:'15% OFF',title:'Selected Home Services',copy:'Premium beauty care in the comfort of your home.',expires:'Ends October 15',tone:'from-[#47373b] to-[#765962]'},
]
const activity=[['Booking confirmed at Luna Beauty Studio','2 hours ago'],['Added Glow Studio to Favorites','Yesterday'],['Reviewed a completed appointment','3 days ago'],['Beauty product order delivered','Last week']]
const notifications=[['Appointment confirmed','Your appointment at Luna Beauty Studio is confirmed.','Now'],['Friendly reminder','Your manicure appointment is tomorrow at 3:00 PM.','2h'],['Order update','Your beauty product order has been shipped.','Yesterday']]

function AuraMark(){return <a href="/dashboard" className="flex items-center gap-2.5 font-display text-2xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-full bg-wine-700 text-white"><Sparkles size={17}/></span>Aura</a>}

export function DashboardNav({active='dashboard'}){
  const {user,logout}=useAuth();const [menu,setMenu]=useState(false)
  const links=[['dashboard','Home','/dashboard'],['salons','Discover Salons','/salons'],['bookings','My Bookings','/my-bookings'],['favorites','Favorites','/favorites'],['notifications','Notifications','/notifications'],['profile','Profile','/profile']]
  const leave=async()=>{await logout();setMenu(false);navigate('/')}
  return <header className="sticky top-0 z-40 border-b border-wine-900/5 bg-[#fbf8f4]/90 backdrop-blur-xl"><div className="wrap flex h-20 items-center justify-between"><AuraMark/><nav className="hidden items-center gap-5 lg:flex" aria-label="Dashboard navigation">{links.slice(0,5).map(([id,label,to])=><a key={id} href={to} className={`text-sm font-semibold transition ${active===id?'text-wine-700':'text-stone-500 hover:text-wine-700'}`}>{label}</a>)}</nav><div className="flex items-center gap-2"><a href="/notifications" aria-label="Notifications, 3 unread" className="relative grid h-10 w-10 place-items-center rounded-full border border-stone-200 bg-white text-stone-600"><Bell size={18}/><span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-wine-700 px-1 text-[10px] font-bold text-white">3</span></a><div className="relative"><button onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Account menu" className="flex items-center gap-2 rounded-full border border-wine-200 bg-white py-1.5 pl-1.5 pr-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-wine-700 text-sm font-bold text-white">{user.name[0]}</span><span className="hidden text-sm font-bold sm:block">{user.name}</span><ChevronDown size={14}/></button>{menu&&<motion.div initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}} className="absolute right-0 mt-2 w-52 rounded-2xl border border-stone-100 bg-white p-2 shadow-card"><a href="/profile" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold hover:bg-wine-50"><UserRound size={16}/>My Profile</a><a href="/profile#settings" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold hover:bg-wine-50"><Settings size={16}/>Settings</a><button onClick={leave} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-red-700 hover:bg-red-50"><LogOut size={16}/>Logout</button></motion.div>}</div></div></div></header>
}

function DashboardHeader({user}){const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';return <section className="flex flex-col justify-between gap-5 rounded-3xl bg-wine-800 p-7 text-white sm:p-9 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/55">Your Aura dashboard</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{greeting}, {user.name}</h1><p className="mt-3 text-white/65">Ready for your next beauty experience?</p></div><div className="flex items-center gap-3 rounded-2xl bg-white/10 p-3 pr-5"><span className="grid h-12 w-12 place-items-center rounded-full bg-white text-lg font-bold text-wine-800">{user.name[0]}</span><div><p className="font-bold">{user.name}</p><p className="text-xs capitalize text-white/55">{user.role} account</p></div></div></section>}

function QuickActions(){return <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{quickActions.map(([Icon,title,copy,to])=><a href={to} key={title} className="group rounded-2xl border border-stone-100 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-wine-200 hover:shadow-card"><span className="grid h-11 w-11 place-items-center rounded-xl bg-wine-50 text-wine-700 group-hover:bg-wine-700 group-hover:text-white"><Icon size={20}/></span><h2 className="mt-4 font-bold">{title}</h2><p className="mt-1 text-xs leading-5 text-stone-500">{copy}</p></a>)}</section>}

function UpcomingAppointment({booking,loading}){if(loading)return <div className="rounded-3xl bg-white p-8 text-sm text-stone-400">Loading your next appointment…</div>;if(!booking)return <div className="rounded-3xl border border-dashed border-wine-200 bg-white p-9 text-center"><CalendarCheck className="mx-auto text-wine-600"/><h3 className="mt-4 font-display text-2xl font-bold">No upcoming appointments</h3><p className="mt-2 text-sm text-stone-500">Your next beauty moment is waiting.</p><a href="/salons" className="btn-primary mt-5 rounded-xl">Book Now</a></div>;return <article className="overflow-hidden rounded-3xl bg-white shadow-card"><div className="grid md:grid-cols-[210px_1fr]"><img src={booking.image} alt="" className="h-52 w-full object-cover md:h-full"/><div className="p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-wine-600">Upcoming Appointment</p><h3 className="mt-2 font-display text-2xl font-bold">{booking.salon}</h3><p className="mt-1 font-semibold text-stone-600">{booking.service} · {booking.specialist}</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{booking.status}</span></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><p><span className="block text-xs text-stone-400">Date & time</span><b>{booking.date}<br/>{booking.time}</b></p><p><span className="block text-xs text-stone-400">Location</span><b>{booking.location}</b></p><p><span className="block text-xs text-stone-400">Booking</span><b>#{booking.id}</b></p></div><div className="mt-5 flex flex-wrap gap-2"><a href="/my-bookings" className="btn-primary rounded-xl px-4 py-2.5 text-sm">View Details</a><a href="/my-bookings" className="btn-secondary rounded-xl px-4 py-2.5 text-sm">Reschedule</a><a target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${encodeURIComponent(booking.address)}`} className="btn-secondary rounded-xl px-4 py-2.5 text-sm"><Navigation size={14}/>Get Directions</a></div></div></div></article>}

function SectionHeading({title,copy,link,label}){return <div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="font-display text-2xl font-bold tracking-[-.03em] sm:text-3xl">{title}</h2>{copy&&<p className="mt-1 text-sm text-stone-500">{copy}</p>}</div>{link&&<a href={link} className="shrink-0 text-sm font-bold text-wine-700">{label} →</a>}</div>}

function ServiceCategories(){return <section className="mt-12"><SectionHeading title="Explore Services" copy="What are you in the mood for?"/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{serviceCategories.map(([symbol,name])=><a key={name} href={`/salons?category=${encodeURIComponent(name)}`} className="rounded-2xl border border-stone-100 bg-white p-4 text-center transition hover:-translate-y-1 hover:border-wine-200 hover:shadow-card"><span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-wine-50 text-lg text-wine-700">{symbol}</span><span className="mt-3 block text-sm font-bold">{name}</span></a>)}</div></section>}

function OffersSection(){return <section className="mt-12"><SectionHeading title="Offers for You" copy="A little more beauty for a little less."/><div className="grid gap-4 lg:grid-cols-3">{offers.map(o=><article key={o.title} className={`rounded-3xl bg-gradient-to-br ${o.tone} p-6 text-white`}><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">{o.discount}</span><h3 className="mt-5 font-display text-2xl font-bold">{o.title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{o.copy}</p><div className="mt-6 flex items-center justify-between"><span className="text-xs text-white/50">{o.expires}</span><a href="/salons" className="rounded-xl bg-white px-4 py-2 text-xs font-bold text-wine-800">View Offer</a></div></article>)}</div></section>}

function ActivityAndNotifications(){return <section className="mt-12 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><SectionHeading title="Recent Activity"/><div className="divide-y divide-stone-100">{activity.map(([text,time])=><div key={text} className="flex gap-3 py-4"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-wine-500"/><div><p className="text-sm font-semibold">{text}</p><p className="mt-1 text-xs text-stone-400">{time}</p></div></div>)}</div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><SectionHeading title="Notifications" link="/notifications" label="View All Notifications"/><div className="space-y-3">{notifications.map(([title,text,time])=><div key={title} className="flex gap-3 rounded-2xl bg-[#faf7f3] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-wine-50 text-wine-700"><Bell size={16}/></span><div><div className="flex items-center gap-2"><p className="text-sm font-bold">{title}</p><span className="text-[10px] text-stone-400">{time}</span></div><p className="mt-1 text-xs leading-5 text-stone-500">{text}</p></div></div>)}</div></div></section>}

function RecentlyViewed({salons}){return <section className="mt-12"><SectionHeading title="Recently Viewed"/><div className="grid gap-3 sm:grid-cols-3">{salons.slice(0,3).map(s=><a key={s.id} href={`/salons/${s.id}`} className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-sm hover:shadow-card"><img src={s.image} alt="" className="h-16 w-16 rounded-xl object-cover"/><div><p className="font-bold">{s.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-stone-400"><MapPin size={11}/>{s.area}</p></div></a>)}</div></section>}

export function CustomerDashboard(){const {user}=useAuth();const [salons,setSalons]=useState([]);const [bookings,setBookings]=useState([]);const [favorites,setFavorites]=useState([]);const [loading,setLoading]=useState(true);const [recentIds]=useState(()=>{if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem('auraRecentlyViewed'))||[]}catch{return []}});useEffect(()=>{let active=true;Promise.all([getSalons(),getMyBookings(user.id),getFavorites(user.id)]).then(([salonRows,bookingRows,favoriteRows])=>{if(!active)return;setSalons(salonRows.map(mapDatabaseSalon));setBookings(bookingRows.map(mapDatabaseBooking));setFavorites(favoriteRows.map(mapDatabaseSalon))}).finally(()=>active&&setLoading(false));return()=>{active=false}},[user.id]);const upcoming=useMemo(()=>bookings.find(b=>b.status==='Confirmed'),[bookings]);const favoriteIds=new Set(favorites.map(s=>s.id));const changeFavorite=async salon=>{const remove=favoriteIds.has(salon.id);await toggleFavorite(user.id,salon.dbId,!remove);setFavorites(items=>remove?items.filter(x=>x.id!==salon.id):[...items,salon])};return <main className="min-h-screen bg-[#f7f2ec]"><DashboardNav/><div className="wrap py-8 sm:py-10"><DashboardHeader user={user}/><QuickActions/><section className="mt-12"><SectionHeading title="Upcoming Appointment" link="/my-bookings" label="My Bookings"/><UpcomingAppointment booking={upcoming} loading={loading}/></section><section className="mt-12"><SectionHeading title="Recommended for You" copy="Highly rated salons selected for your next visit." link="/salons" label="Discover All"/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{salons.slice(0,4).map(s=><SalonCard key={s.id} salon={s} favorite={favoriteIds.has(s.id)} onFavorite={()=>changeFavorite(s)}/>)}</div></section><section className="mt-12"><SectionHeading title="Your Favorites" copy="Your saved beauty destinations." link="/favorites" label="View All Favorites"/>{favorites.length?<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{favorites.slice(0,3).map(s=><SalonCard key={s.id} salon={s} favorite onFavorite={()=>changeFavorite(s)}/>)}</div>:<div className="rounded-3xl border border-dashed border-wine-200 bg-white p-8 text-center"><Heart className="mx-auto text-wine-500"/><p className="mt-3 font-bold">Save salons you love</p><a href="/salons" className="mt-2 inline-block text-sm font-bold text-wine-700">Discover salons →</a></div>}</section><ServiceCategories/><OffersSection/><ActivityAndNotifications/><RecentlyViewed salons={recentIds.map(id=>salons.find(s=>s.id===id)).filter(Boolean)}/></div></main>}

export function FavoritesPage(){const {user}=useAuth();const [items,setItems]=useState([]);useEffect(()=>{getFavorites(user.id).then(rows=>setItems(rows.map(mapDatabaseSalon)))},[user.id]);const remove=async salon=>{await toggleFavorite(user.id,salon.dbId,false);setItems(xs=>xs.filter(x=>x.id!==salon.id))};return <main className="min-h-screen bg-[#f7f2ec]"><DashboardNav active="favorites"/><div className="wrap py-10"><SectionHeading title="Your Favorites" copy="The salons you saved for later."/>{items.length?<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(s=><SalonCard key={s.id} salon={s} favorite onFavorite={()=>remove(s)}/>)}</div>:<div className="rounded-3xl bg-white p-14 text-center"><Heart className="mx-auto text-wine-500"/><h2 className="mt-4 font-display text-2xl font-bold">No favorites yet</h2><a href="/salons" className="btn-primary mt-5 rounded-xl">Discover Salons</a></div>}</div></main>}

export function NotificationsPage(){return <main className="min-h-screen bg-[#f7f2ec]"><DashboardNav active="notifications"/><div className="wrap max-w-4xl py-10"><SectionHeading title="Notifications" copy="Your latest Aura updates and reminders."/><div className="space-y-3">{notifications.concat([['Offer just for you','Enjoy 15% off selected home services.','3 days ago']]).map(([title,text,time])=><article key={title} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-wine-50 text-wine-700"><Bell size={18}/></span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-stone-500">{text}</p><p className="mt-2 text-xs text-stone-400">{time}</p></div></article>)}</div></div></main>}
